name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install Python dependencies
        run: |
          cd backend
          pip install pipenv
          pipenv install --dev
      
      - name: Install Node dependencies
        run: |
          cd frontend
          npm ci
      
      - name: Type check frontend
        run: |
          cd frontend
          npm run typecheck
      
      - name: Lint frontend
        run: |
          cd frontend
          npm run lint

      # Add actual test commands here
      - name: Run frontend tests
        run: |
          cd frontend
          npm test

      - name: Run backend tests
        run: |
          cd backend
          pipenv run python -m pytest