name: Config

on:
  workflow_dispatch:

jobs:
  configure-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - uses: actions/checkout@v4

      - name: Configure Branch Protection
        env:
          GITHUB_TOKEN: ${{ secrets.FINE_GRAINED_PAT }}
          REPO: ${{ github.repository }}
        run: |
          gh api --method PUT /repos/${REPO}/branches/main/protection \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --field required_status_checks='{"strict":true,"contexts":["test"]}' \
            --field enforce_admins=false \
            --field required_pull_request_reviews='{"dismissal_restrictions":{},"dismiss_stale_reviews":true,"require_code_owner_reviews":false,"required_approving_review_count":1,"bypass_pull_request_allowances":{"users":["${{ github.repository_owner }}"]}}' \
            --field restrictions=null

      - name: Configure Repository Settings
        env:
          GITHUB_TOKEN: ${{ secrets.FINE_GRAINED_PAT }}
          REPO: ${{ github.repository }}
        run: |
          gh api --method PATCH /repos/${REPO} \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --field allow_squash_merge=true \
            --field allow_merge_commit=false \
            --field allow_rebase_merge=false \
            --field delete_branch_on_merge=true